### PR TITLE
Various Fixes

### PR DESCRIPTION
**Pull request by kingthorin**
- Add displaytext front matter element to have decent looking tab names. 
- Remove Gemfile.lock. 
- Update .gitignore to include Gemfile.lock. [Should not be kept in the repo, latest dependencies should always be used.]
- Remove tab_example.md which is unused and no longer necessary.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Ping @latf6711 @bugwrangler

**Comment by kingthorin** [comment]
Is this chapter still alive?

**Comment by latf6711** [comment]
All active chapter are listed https://owasp.org/chapters/

https://owasp.org/www-chapter-bangalore/

**Comment by kingthorin** [comment]
Hello chapter leaders?????

**Comment by kingthorin** [comment]
Hello chapter leaders?????

**Comment by vermava** [comment]
Apologies for the delay, Merged the changes.

**Pull request merged**
